export const number = [
    { text: '9' },
    { text: '8' },
    { text: '7' },
    { text: '(' },
    { text: ')' },
    { text: '6' },
    { text: '5' },
    { text: '4' },
    { text: '<' },
    { text: '>' },
    { text: '3' },
    { text: '2' },
    { text: '1' },
    { text: '/' },
    { text: '*' },
    { text: '%' },
    { text: '0' },
    { text: '.' },
    { text: '-' },
    { text: '+' },
]