export const numeric = [
    { text: 'sin(', operation: 'Math.sin(' },
    { text: 'cos(', operation: 'Math.cos(' },
    { text: 'tan(', operation: 'Math.tan(' },
    { text: 'log(', operation: 'Math.log10(' },
    { text: '<' },
    { text: '>' },
    { text: '√', operation: 'Math.sqrt(' },
    { text: '^' },
    { text: '(' },
    { text: ')' },
    { text: '%' },
    { text: 'π', operation: 'Math.PI' },
    { text: '7' },
    { text: '8' },
    { text: '9' },
    { text: '/' },
    { text: '*' },
    { text: '6' },
    { text: '5' },
    { text: '4' },
    { text: '+' },
    { text: '-' },
    { text: '3' },
    { text: '2' },
    { text: '1' },
    { text: '.' },
    { text: '0' },
];